import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "@next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100","200","300","400","500","600","700","800","900"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const logoFont = localFont({
  src: "./fonts/Karla-VariableFont_wght.ttf",
  variable: "--font-logo",
  weight: "100 900",
});

export const metadata = {
  title: "Dive Deeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${logoFont.variable} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
